# This is a workflow to deploy tags and update lastmod via automation
# Author : ColdFusionX

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs Publish & Lastmod script
      - name: Publish script
        run: |
          bash tools/publish.sh
          
      - name: Lastmod script
        run: |
          bash _scripts/sh/dump_lastmod.sh        
